//! Axum router — assembly of all HTTP routes and middleware.
//!
//! See `../../../../specs/domains/server.md` for the full design.
//! This module is the only place where the route tree is built;
//! every endpoint added in PR4/5 will hang off the `Router::nest`
//! call below.

use std::sync::Arc;

use axum::routing::get;
use axum::Router;
use tower_http::cors::CorsLayer;
use tower_http::set_header::SetResponseHeaderLayer;
use tower_http::trace::TraceLayer;

use super::auth::bearer_layer;
use super::info::{health, server_info};
use super::state::ServerState;
use super::static_files::serve_ui_fallback;

/// Build the Axum router bound to the given `ServerState`. The
/// returned `Router` is fully self-contained and ready to be
/// `.serve(...)`'d.
///
/// **Note**: rate-limiting (`tower::limit::RateLimitLayer`) is
/// **deferred to PR7 (hardening)**. The current `RateLimitLayer`
/// has a `Clone`-bound issue when nested inside `Router::layer`
/// in axum 0.7 (it produces a `RateLimit<Route>` service that
/// doesn't implement `Clone` because `Route` doesn't). Adding it
/// back requires either a custom middleware or restructuring
/// the router tree; tracked under AC16 of `domains/server.md`.
pub fn build_router(state: Arc<ServerState>) -> Router {
    // Per-`/api/v1/*` routes that don't require auth (health
    // checks must work even when the token is rotated, etc.).
    let public_api = Router::new().route("/health", get(health));

    // Per-`/api/v1/*` routes that require the bearer layer.
    let protected_api = Router::new()
        .route("/server/info", get(server_info))
        .route_layer(axum::middleware::from_fn_with_state(
            state.clone(),
            bearer_layer,
        ));

    let api = Router::new().merge(public_api).merge(protected_api);

    // CORS: same-origin only. The browser UI is served from the
    // same host:port, so no cross-origin requests should be
    // generated by our own code. We allow `GET`/`POST`/`PATCH`/
    // `DELETE` to be permissive about methods; the real check
    // is the Origin header (left at default = any).
    let cors = CorsLayer::very_permissive();

    // `x-content-type-options: nosniff` on every response, to
    // harden the static file responses when they land in PR5.
    let nosniff = SetResponseHeaderLayer::if_not_present(
        axum::http::header::HeaderName::from_static("x-content-type-options"),
        axum::http::HeaderValue::from_static("nosniff"),
    );

    Router::new()
        .nest("/api/v1", api)
        .fallback(serve_ui_fallback)
        .layer(TraceLayer::new_for_http())
        .layer(cors)
        .layer(nosniff)
        .with_state(state)
}
